# Fraud Monitoring — Publisher-Level Install Analysis

Hourly install patterns, CPI, and retention (D1/D3) by publisher for a given bundle, OS, and geo.

In [71]:
#@title Colab Authentication

from google.colab import auth
auth.authenticate_user()

In [72]:
#@title Environment Setup
from google.cloud import bigquery
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_colwidth', 80)

client = bigquery.Client(project='moloco-ods')

def run_query(query, label=''):
    try:
        df = client.query(query).result().to_dataframe()
        status = f'✅ {label}: {len(df)} rows' if len(df) > 0 else f'⚠️ {label}: 0 rows'
        print(status)
        return df
    except Exception as e:
        print(f'❌ {label}: {e}')
        return pd.DataFrame()

_pub_name_cache = {}

def enrich_publisher_names(df, bundle_col='publisher_bundle'):
    """Add publisher_name column by looking up dim1_app_with_tracking_publisher_v2."""
    if df.empty or bundle_col not in df.columns:
        return df
    missing = set(df[bundle_col].unique()) - set(_pub_name_cache.keys())
    if missing:
        bids = ", ".join(f"'{b}'" for b in missing)
        q = f"""SELECT DISTINCT app_market_bundle, app_name
                FROM `moloco-ae-view.athena.dim1_app_with_tracking_publisher_v2`
                WHERE app_market_bundle IN ({bids})"""
        try:
            rows = client.query(q).result()
            for r in rows:
                _pub_name_cache[r.app_market_bundle] = r.app_name
        except Exception:
            pass
    df = df.copy()
    df.insert(df.columns.get_loc(bundle_col) + 1, 'publisher_name',
              df[bundle_col].map(_pub_name_cache).fillna(''))
    return df

## Parameters

In [73]:
#@title Parameters
#@markdown **Priority: CAMPAIGN_IDS > MMP_BUNDLE_IDS.**  If campaign IDs are set, bundle/OS/country are derived from them.

CAMPAIGN_IDS_STR = "naoP7qVSZwYbv4GY, unbUzFob1WCmTrVD, jVkXbQ2LIdIKoaQg"  #@param {type:"string"}
MMP_BUNDLE_IDS_STR = ""  #@param {type:"string"}
COUNTRIES_STR = ""  #@param {type:"string"}
LOOKBACK_DAYS = 7  #@param {type:"integer"}

CAMPAIGN_IDS = [s.strip() for s in CAMPAIGN_IDS_STR.split(",") if s.strip()]
MMP_BUNDLE_IDS = [s.strip() for s in MMP_BUNDLE_IDS_STR.split(",") if s.strip()]
COUNTRIES = [s.strip() for s in COUNTRIES_STR.split(",") if s.strip()]

# --- determine mode & build SQL fragments ---
# Output dimension: <OS:Country>  (e.g. "ANDROID:KOR")
# Timezone: KST (UTC+9) for hourly data; daily tables use UTC partition dates.
_MODE = 'campaign' if CAMPAIGN_IDS else 'bundle'
_TZ = 'Asia/Seoul'

_os_country_expr     = "CONCAT(campaign.os, ':', campaign.country)"
_os_country_expr_cv  = "CONCAT(req.device.os, ':', req.device.geo.country)"

if _MODE == 'campaign':
    _ids = ", ".join(f"'{c}'" for c in CAMPAIGN_IDS)
    _where_filter = f"AND campaign_id IN ({_ids})"
    _where_filter_cv = f"AND api.campaign.id IN ({_ids})"
    _extra_select = f"campaign_id, {_os_country_expr} AS os_country,"
    _extra_select_cv = f"api.campaign.id AS campaign_id, {_os_country_expr_cv} AS os_country,"
    _extra_group = f"campaign_id, {_os_country_expr},"
    _extra_group_cv = f"api.campaign.id, {_os_country_expr_cv},"
    _dim_cols = ['campaign_id', 'os_country']
else:
    _bids = ", ".join(f"'{b}'" for b in MMP_BUNDLE_IDS)
    _where_filter = f"AND advertiser.mmp_bundle_id IN ({_bids})"
    _where_filter_cv = f"AND api.product.app.tracking_bundle IN ({_bids})"
    _extra_select = f"{_os_country_expr} AS os_country,"
    _extra_select_cv = f"{_os_country_expr_cv} AS os_country,"
    _extra_group = f"{_os_country_expr},"
    _extra_group_cv = f"{_os_country_expr_cv},"
    _dim_cols = ['os_country']

if COUNTRIES:
    _clist = ", ".join(f"'{c}'" for c in COUNTRIES)
    _where_filter += f"\n  AND campaign.country IN ({_clist})"
    _where_filter_cv += f"\n  AND req.device.geo.country IN ({_clist})"

print(f'Mode:      {_MODE}')
if _MODE == 'campaign':
    print(f'Campaigns: {CAMPAIGN_IDS}')
else:
    print(f'Bundles:   {MMP_BUNDLE_IDS}')
print(f'Countries: {COUNTRIES or "(all)"}')
print(f'Timezone:  KST (UTC+9)')
print(f'Lookback:  {LOOKBACK_DAYS} days')

Mode:      campaign
Campaigns: ['naoP7qVSZwYbv4GY', 'unbUzFob1WCmTrVD', 'jVkXbQ2LIdIKoaQg']
Countries: (all)
Timezone:  KST (UTC+9)
Lookback:  7 days

---

In [74]:
# placeholder

---
## 1. Daily Publisher Summary (installs, CPI, retention)

In [75]:
#1. Daily Publisher Summary — installs, CPI, D1/D3 retention

q_pub = f"""
SELECT
  {_extra_select}
  date_utc,
  publisher.app_market_bundle AS publisher_bundle,
  SUM(installs) AS installs,
  SUM(installs_rejected) AS installs_rejected,
  ROUND(SUM(gross_spend_usd), 2) AS spend_usd,
  ROUND(SAFE_DIVIDE(SUM(gross_spend_usd), NULLIF(SUM(installs), 0)), 2) AS cpi,
  SUM(impressions) AS impressions,
  SUM(clicks) AS clicks,
  ROUND(SAFE_DIVIDE(SUM(retained_users_d1), NULLIF(SUM(installs), 0)) * 100, 1) AS retention_d1_pct,
  ROUND(SAFE_DIVIDE(SUM(retained_users_d3), NULLIF(SUM(installs), 0)) * 100, 1) AS retention_d3_pct,
  ROUND(SAFE_DIVIDE(SUM(clicks), NULLIF(SUM(impressions), 0)) * 100, 2) AS ctr_pct
FROM `moloco-ae-view.athena.fact_dsp_publisher`
WHERE date_utc BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL {LOOKBACK_DAYS} DAY) AND CURRENT_DATE()
  {_where_filter}
GROUP BY {_extra_group} date_utc, publisher.app_market_bundle
HAVING installs > 0
ORDER BY date_utc DESC, installs DESC
"""

df_pub = run_query(q_pub, '1. Daily Publisher Summary')
if not df_pub.empty:
    df_pub = enrich_publisher_names(df_pub)
    numeric_cols = ['installs', 'installs_rejected', 'spend_usd', 'cpi', 'impressions', 'clicks',
                    'retention_d1_pct', 'retention_d3_pct', 'ctr_pct']
    for col in numeric_cols:
        if col in df_pub.columns:
            df_pub[col] = pd.to_numeric(df_pub[col], errors='coerce')

    for oc in sorted(df_pub['os_country'].unique()):
        sub = df_pub[df_pub['os_country'] == oc]
        agg = sub.groupby(['publisher_bundle', 'publisher_name']).agg(
            total_installs=('installs', 'sum'),
            total_spend=('spend_usd', 'sum'),
            total_impressions=('impressions', 'sum'),
            total_clicks=('clicks', 'sum'),
        ).sort_values('total_installs', ascending=False)
        agg['cpi'] = (agg['total_spend'] / agg['total_installs']).round(2)
        agg['ctr_pct'] = (agg['total_clicks'] / agg['total_impressions'] * 100).round(2)

        print(f'\n  [{oc}] Top publishers (L{LOOKBACK_DAYS}D):')
        for (pub, name), row in agg.head(10).iterrows():
            label = f'{name[:30]} ({pub[:30]})' if name else pub[:50]
            print(f'    {label:65s}  installs={row["total_installs"]:>6,.0f}  CPI=${row["cpi"]:.2f}  CTR={row["ctr_pct"]:.2f}%')
df_pub

✅ 1. Daily Publisher Summary: 1064 rows

  [ANDROID:ARE] Top publishers (L7D):
    com.auto.war.crash.arena                            installs=     1  CPI=$0.00  CTR=100.00%
    com.rheia.patrino                                   installs=     1  CPI=$0.11  CTR=50.00%
    qiblafinder.prayertimes.qibladirection.hijricalend  installs=     1  CPI=$0.04  CTR=100.00%
    me.pokeraid                                         installs=     1  CPI=$0.00  CTR=0.00%
    info.t4w.vp                                         installs=     1  CPI=$0.21  CTR=12.50%
    com.wool.puzzle.game3d                              installs=     1  CPI=$0.22  CTR=20.00%
    com.studion.mergearena                              installs=     1  CPI=$0.02  CTR=42.86%
    com.scores365                                       installs=     1  CPI=$0.72  CTR=11.11%
    com.multicastgames.butcher                          installs=     1  CPI=$2.73  CTR=25.58%
    com.battle.worldofartillery                         installs=     1  CPI=$0.08  CTR=100.00%

  [ANDROID:AUS] Top publishers (L7D):
    com.Jbm360.ModernTowerDefense                       installs=     1  CPI=$0.20  CTR=66.67%
    com.domobile.applockwatcher                         installs=     1  CPI=$0.00  CTR=0.00%
    com.dream.dale                                      installs=     1  CPI=$0.35  CTR=50.00%
    com.finetosurvive.master                            installs=     1  CPI=$0.28  CTR=15.38%
    com.flyingwhalegames.carout                         installs=     1  CPI=$0.03  CTR=100.00%
    com.ftt.msleague_gl                                 installs=     1  CPI=$1.80  CTR=75.00%
    com.gramgames.mergedragons                          installs=     1  CPI=$0.38  CTR=100.00%
    com.idlesupernaturalschool.jlyt                     installs=     1  CPI=$0.04  CTR=0.00%
    com.medieval.punk                                   installs=     1  CPI=$0.87  CTR=50.00%
    com.nebula.mahjongtile                              installs=     1  CPI=$0.40  CTR=25.00%

  [ANDROID:AUT] Top publishers (L7D):
    autoclicker.clicker.autoclickerapp.autoclickerforg  installs=     1  CPI=$0.08  CTR=100.00%
    com.pixel.art.coloring.color.number.paint.skull     installs=     1  CPI=$0.03  CTR=33.33%
    storage.manager.ora                                 installs=     1  CPI=$0.09  CTR=100.00%
    hero.claw.master                                    installs=     1  CPI=$0.78  CTR=53.85%
    com.zombie.idleminertycoon                          installs=     1  CPI=$0.35  CTR=47.37%
    com.unicostudio.minerfighters                       installs=     1  CPI=$0.10  CTR=25.00%
    com.tripledot.woodoku                               installs=     1  CPI=$0.09  CTR=20.00%
    com.snake.slayer                                    installs=     1  CPI=$0.17  CTR=100.00%
    com.shooterhero                                     installs=     1  CPI=$0.04  CTR=80.00%
    com.paxiegames.snakepuzzle                          installs=     1  CPI=$1.59  CTR=15.79%

  [ANDROID:BEL] Top publishers (L7D):
    hero.claw.master                                    installs=     2  CPI=$0.38  CTR=43.90%
    com.weward                                          installs=     2  CPI=$0.40  CTR=75.00%
    com.naver.linewebtoon                               installs=     2  CPI=$0.66  CTR=2.29%
    ai.socialapps.speakmaster                           installs=     1  CPI=$0.05  CTR=37.50%
    com.pieyel.scrabble                                 installs=     1  CPI=$0.01  CTR=44.44%
    io.supercent.weaponrpg                              installs=     1  CPI=$0.46  CTR=59.38%
    io.supercent.linkedcubic                            installs=     1  CPI=$0.10  CTR=50.00%
    defense.roguelike.cell.shoot.survivor               installs=     1  CPI=$1.02  CTR=37.63%
    com.weaver.app.prod                                 installs=     1  CPI=$0.57  CTR=37.50%
    com.wa.cult.empire.tycoon.idle.game                 installs=     1  CPI=$0.24  CTR=45.45%

  [ANDROID:CAN] Top publishers (L7D):
    com.bighelmets.destiny                              installs=     2  CPI=$0.51  CTR=43.75%
    com.anibox.catpark                                  installs=     1  CPI=$0.29  CTR=100.00%
    com.my.defense                                      installs=     1  CPI=$2.69  CTR=57.14%
    kr.co.vcnc.android.couple                           installs=     1  CPI=$0.00  CTR=0.00%
    games.vaveda.militaryoverturn                       installs=     1  CPI=$0.01  CTR=20.00%
    com.vitastudio.mahjong                              installs=     1  CPI=$0.16  CTR=55.56%
    com.traverse.zhfx.en.gp                             installs=     1  CPI=$10.15  CTR=48.21%
    com.tombminer.idle.merge                            installs=     1  CPI=$0.10  CTR=71.43%
    com.sugargames.bot                                  installs=     1  CPI=$0.05  CTR=20.00%
    com.pc.sand.loop                                    installs=     1  CPI=$0.07  CTR=33.33%

  [ANDROID:CHE] Top publishers (L7D):
    mech.fortress.tower.defense.hero.war                installs=     2  CPI=$0.35  CTR=100.00%
    com.actfirstgames.seven                             installs=     1  CPI=$0.03  CTR=0.00%
    com.bibiboom.settlementheroes                       installs=     1  CPI=$0.04  CTR=50.00%
    com.circle38.photocircle                            installs=     1  CPI=$0.00  CTR=0.00%
    com.eastsidegames.doctorwho                         installs=     1  CPI=$0.77  CTR=20.00%
    com.gamebasics.afm                                  installs=     1  CPI=$0.89  CTR=25.00%
    com.hotheadgames.google.beta.idle_golf              installs=     1  CPI=$0.08  CTR=50.00%
    com.panteon.arcanearena                             installs=     1  CPI=$0.18  CTR=62.50%
    com.sugargames.bot                                  installs=     1  CPI=$0.20  CTR=33.33%
    house.geeky.mergeevolution                          installs=     1  CPI=$0.10  CTR=75.00%

  [ANDROID:CYP] Top publishers (L7D):
    com.DefaultCompany.HoboLife                         installs=     1  CPI=$0.40  CTR=50.00%
    com.alleylabs.battlegrounds                         installs=     1  CPI=$0.00  CTR=nan%
    com.callapp.contacts                                installs=     1  CPI=$0.01  CTR=0.00%
    com.hwqgrhhjfd.idlefastfood                         installs=     1  CPI=$0.07  CTR=50.00%
    hero.claw.master                                    installs=     1  CPI=$0.03  CTR=50.00%

  [ANDROID:DEU] Top publishers (L7D):
    defense.roguelike.cell.shoot.survivor               installs=     4  CPI=$6.67  CTR=37.88%
    net.lovoo.android                                   installs=     4  CPI=$0.49  CTR=5.77%
    com.ebay.kleinanzeigen                              installs=     4  CPI=$0.38  CTR=1.57%
    com.ecffri.arrows                                   installs=     4  CPI=$0.82  CTR=62.89%
    train.ride.master                                   installs=     3  CPI=$0.66  CTR=53.85%
    com.pockethaven.roguelegend                         installs=     3  CPI=$3.58  CTR=45.16%
    com.vitastudio.mahjong                              installs=     2  CPI=$1.67  CTR=40.20%
    com.innogames.heroesofhistory                       installs=     2  CPI=$3.14  CTR=33.88%
    hero.claw.master                                    installs=     2  CPI=$2.81  CTR=45.24%
    com.global.sgdbzseaeu                               installs=     2  CPI=$0.10  CTR=100.00%

  [ANDROID:ESP] Top publishers (L7D):
    com.pockethaven.roguelegend                         installs=     2  CPI=$0.36  CTR=35.71%
    com.multicastgames.butcher                          installs=     2  CPI=$0.74  CTR=6.19%
    com.sybogames.subway.surfers.game                   installs=     2  CPI=$0.34  CTR=0.00%
    com.FishEatFish.FeedGrow                            installs=     1  CPI=$0.29  CTR=100.00%
    my.arena                                            installs=     1  CPI=$0.81  CTR=16.67%
    jp.co.goodroid.hyper.hexaaway                       installs=     1  CPI=$0.00  CTR=0.00%
    games.resourcer.hex                                 installs=     1  CPI=$0.10  CTR=0.00%
    es.socialpoint.MonsterLegends                       installs=     1  CPI=$0.22  CTR=42.86%
    com.wallapop                                        installs=     1  CPI=$0.08  CTR=0.00%
    com.traveler.journey                                installs=     1  CPI=$0.01  CTR=100.00%

  [ANDROID:FRA] Top publishers (L7D):
    com.block.juggle                                    installs=     7  CPI=$0.74  CTR=17.29%
    defense.roguelike.cell.shoot.survivor               installs=     5  CPI=$3.13  CTR=36.47%
    com.naver.linewebtoon                               installs=     4  CPI=$4.08  CTR=5.17%
    com.evodefensetd.gp                                 installs=     4  CPI=$0.31  CTR=25.23%
    fr.vinted                                           installs=     4  CPI=$0.10  CTR=0.00%
    com.dong.hexwarriors                                installs=     4  CPI=$0.39  CTR=38.89%
    com.alleylabs.battlegrounds                         installs=     3  CPI=$0.31  CTR=38.71%
    com.smallgiantgames.empires                         installs=     3  CPI=$0.40  CTR=34.38%
    com.epicoro.castleclashers                          installs=     3  CPI=$0.51  CTR=49.57%
    com.ecffri.arrows                                   installs=     3  CPI=$1.42  CTR=57.47%

  [ANDROID:GBR] Top publishers (L7D):
    com.traverse.zhfx.en.gp                             installs=     4  CPI=$5.62  CTR=47.48%
    games.resourcer.hex                                 installs=     3  CPI=$0.18  CTR=20.00%
    com.block.juggle                                    installs=     2  CPI=$1.22  CTR=9.54%
    com.ecffri.arrows                                   installs=     2  CPI=$0.41  CTR=53.19%
    com.easybrain.crossword.puzzles                     installs=     2  CPI=$0.26  CTR=14.00%
    com.redcellgames.animalvalley                       installs=     2  CPI=$0.23  CTR=55.56%
    tycoon.building.simulator.games.aldagames.com       installs=     2  CPI=$0.46  CTR=36.84%
    com.privatesub.ringdale.idle                        installs=     1  CPI=$0.07  CTR=40.00%
    com.popve.dicevmonster                              installs=     1  CPI=$0.30  CTR=66.67%
    com.polygon.arena                                   installs=     1  CPI=$0.02  CTR=100.00%

  [ANDROID:HKG] Top publishers (L7D):
    com.lihkg.app                                       installs=     4  CPI=$0.37  CTR=0.86%
    com.com2usholdings.starsailors.android.google.glob  installs=     1  CPI=$0.41  CTR=50.00%
    com.intsig.camscanner                               installs=     1  CPI=$0.19  CTR=22.22%
    easy.sudoku.puzzle.solver.free                      installs=     1  CPI=$1.14  CTR=2.56%

  [ANDROID:HUN] Top publishers (L7D):
    studio.powerplay.lktycoon                           installs=     2  CPI=$0.12  CTR=66.67%
    io.supercent.ageofdinosaurs                         installs=     2  CPI=$0.11  CTR=70.97%
    hero.claw.master                                    installs=     2  CPI=$0.59  CTR=57.85%
    com.epicoro.castleclashers                          installs=     2  CPI=$0.30  CTR=48.00%
    com.venturesis.trap                                 installs=     2  CPI=$0.26  CTR=40.00%
    adventure.party.real.life                           installs=     1  CPI=$0.23  CTR=38.46%
    com.vincentb.MobControl                             installs=     1  CPI=$0.14  CTR=11.43%
    com.popve.dicevmonster                              installs=     1  CPI=$0.06  CTR=41.67%
    com.red.arrows.android                              installs=     1  CPI=$0.11  CTR=33.33%
    com.sled.surfers.game                               installs=     1  CPI=$0.11  CTR=50.00%

  [ANDROID:IDN] Top publishers (L7D):
    com.traverse.zhfx.en.gp                             installs=    16  CPI=$6.46  CTR=46.74%
    com.worldance.drama                                 installs=     9  CPI=$1.48  CTR=24.31%
    com.freereels.app                                   installs=     6  CPI=$2.05  CTR=66.94%
    com.nvsgames.pt                                     installs=     5  CPI=$1.24  CTR=24.66%
    com.naver.linewebtoon                               installs=     4  CPI=$1.55  CTR=5.17%
    defense.roguelike.cell.shoot.survivor               installs=     4  CPI=$11.85  CTR=43.14%
    hero.claw.master                                    installs=     4  CPI=$2.70  CTR=48.31%
    my.arena                                            installs=     3  CPI=$8.52  CTR=30.75%
    com.bstar.intl                                      installs=     3  CPI=$1.66  CTR=22.68%
    com.michatapp.im                                    installs=     3  CPI=$2.35  CTR=35.29%

  [ANDROID:IRL] Top publishers (L7D):
    com.deadroad.zhighway                               installs=     1  CPI=$0.20  CTR=75.00%
    com.jlyt.SurvivorIsland                             installs=     1  CPI=$0.08  CTR=100.00%
    com.mobirate.DeadAheadTactics                       installs=     1  CPI=$1.16  CTR=100.00%
    park.dragon.pocket.match                            installs=     1  CPI=$0.17  CTR=100.00%
    spell.word.screw.sort.puzzle                        installs=     1  CPI=$0.28  CTR=75.00%

  [ANDROID:ITA] Top publishers (L7D):
    autoclicker.clicker.autoclickerapp.autoclickerforg  installs=     1  CPI=$0.05  CTR=50.00%
    com.pockethaven.roguelegend                         installs=     1  CPI=$1.17  CTR=57.14%
    net.ajcloud.universal                               installs=     1  CPI=$0.00  CTR=0.00%
    io.supercent.linkedcubic                            installs=     1  CPI=$0.80  CTR=20.00%
    heroes.magic.strategy.fantasy.card.game             installs=     1  CPI=$2.96  CTR=25.00%
    defense.roguelike.cell.shoot.survivor               installs=     1  CPI=$1.52  CTR=28.57%
    com.whalergames.pirateraid                          installs=     1  CPI=$3.85  CTR=25.00%
    com.wa.cult.empire.tycoon.idle.game                 installs=     1  CPI=$1.42  CTR=52.63%
    com.vitastudio.mahjong                              installs=     1  CPI=$6.63  CTR=29.79%
    com.vincentb.MobControl                             installs=     1  CPI=$1.28  CTR=15.79%

  [ANDROID:KWT] Top publishers (L7D):
    com.gaman.games.leek.factory.tycoon                 installs=     1  CPI=$0.04  CTR=42.86%
    com.king.candycrushsaga                             installs=     1  CPI=$0.01  CTR=100.00%
    com.rapid.short.tv                                  installs=     1  CPI=$0.04  CTR=66.67%
    info.t4w.vp                                         installs=     1  CPI=$0.03  CTR=14.29%
    io.supercent.bigslimemanyslime                      installs=     1  CPI=$0.04  CTR=50.00%
    io.voodoo.paper2                                    installs=     1  CPI=$0.08  CTR=100.00%

  [ANDROID:MYS] Top publishers (L7D):
    com.grindrapp.android                               installs=     3  CPI=$1.70  CTR=3.39%
    com.traverse.zhfx.en.gp                             installs=     3  CPI=$14.92  CTR=48.05%
    defense.roguelike.cell.shoot.survivor               installs=     3  CPI=$11.39  CTR=36.38%
    com.ecffri.arrows                                   installs=     2  CPI=$2.86  CTR=53.33%
    com.IdleMagicSchool.jlyt                            installs=     2  CPI=$0.57  CTR=55.56%
    com.bag.fight.backpack.critter.battle.rumble.paws   installs=     2  CPI=$3.39  CTR=45.71%
    games.resourcer.hex                                 installs=     1  CPI=$0.99  CTR=13.89%
    jp.co.imagineer.medarotsurvivors                    installs=     1  CPI=$4.84  CTR=30.43%
    com.zzdmx.sfgame                                    installs=     1  CPI=$0.00  CTR=nan%
    com.qxgame.gmerge                                   installs=     1  CPI=$1.61  CTR=15.38%

  [ANDROID:NLD] Top publishers (L7D):
    com.bag.fight.backpack.critter.battle.rumble.paws   installs=     2  CPI=$0.25  CTR=53.33%
    com.studio501.cuphero                               installs=     2  CPI=$1.57  CTR=50.00%
    com.mathbrain.sudoku                                installs=     2  CPI=$0.12  CTR=41.67%
    com.Beauchamp.Messenger.external                    installs=     1  CPI=$0.03  CTR=75.00%
    com.pc.sand.loop                                    installs=     1  CPI=$0.13  CTR=36.36%
    spell.word.screw.sort.puzzle                        installs=     1  CPI=$0.31  CTR=14.00%
    rail.road.tycoon                                    installs=     1  CPI=$0.09  CTR=100.00%
    com.zykj.princessknight                             installs=     1  CPI=$0.31  CTR=50.00%
    com.zeptolab.thieves.google                         installs=     1  CPI=$0.02  CTR=75.00%
    com.unimob.idle.army                                installs=     1  CPI=$0.01  CTR=100.00%

  [ANDROID:NOR] Top publishers (L7D):
    com.appideas.minimonsters                           installs=     1  CPI=$0.19  CTR=27.27%
    com.brain.crazy.joygame                             installs=     1  CPI=$0.01  CTR=100.00%
    com.evolution.merge                                 installs=     1  CPI=$0.58  CTR=20.00%
    com.hybridparking.game                              installs=     1  CPI=$0.20  CTR=100.00%
    com.oreon.trapall                                   installs=     1  CPI=$0.11  CTR=66.67%
    com.popve.dicevmonster                              installs=     1  CPI=$0.09  CTR=0.00%

  [ANDROID:NZL] Top publishers (L7D):
    com.IdleMagicSchool.jlyt                            installs=     1  CPI=$0.23  CTR=50.00%
    com.ecffri.arrows                                   installs=     1  CPI=$0.03  CTR=100.00%
    com.evodefensetd.gp                                 installs=     1  CPI=$0.09  CTR=33.33%
    com.moonlight.elemon                                installs=     1  CPI=$0.00  CTR=nan%
    com.nebula.mahjongtile                              installs=     1  CPI=$0.45  CTR=90.91%
    com.rbx.battle.android                              installs=     1  CPI=$0.09  CTR=50.00%
    com.rockydessert.travelcenter                       installs=     1  CPI=$0.22  CTR=75.00%
    com.tapped.zsurvivor                                installs=     1  CPI=$0.10  CTR=100.00%
    com.tree.godown                                     installs=     1  CPI=$0.19  CTR=14.29%
    heroes.battle.strategy.card.game                    installs=     1  CPI=$1.16  CTR=66.67%

  [ANDROID:POL] Top publishers (L7D):
    com.studio501.cuphero                               installs=     4  CPI=$0.65  CTR=29.38%
    com.sybogames.subway.surfers.game                   installs=     3  CPI=$0.24  CTR=14.29%
    com.evodefensetd.gp                                 installs=     3  CPI=$0.58  CTR=17.04%
    heroes.battle.strategy.card.game                    installs=     3  CPI=$3.23  CTR=33.82%
    hero.claw.master                                    installs=     3  CPI=$0.96  CTR=55.80%
    com.newleaf.app.android.victor                      installs=     3  CPI=$0.83  CTR=34.07%
    com.block.juggle                                    installs=     2  CPI=$0.92  CTR=31.58%
    com.futureplay.boots                                installs=     2  CPI=$0.14  CTR=25.00%
    com.samsung.android.game.gamehome                   installs=     2  CPI=$0.31  CTR=0.35%
    com.easybrain.crossword.puzzles                     installs=     2  CPI=$0.58  CTR=10.65%

  [ANDROID:QAT] Top publishers (L7D):
    com.bstar.intl                                      installs=     1  CPI=$0.02  CTR=50.00%
    com.cookapps.idlebackpacker                         installs=     1  CPI=$0.04  CTR=100.00%
    com.ttt.fortressmerge                               installs=     1  CPI=$0.12  CTR=87.50%
    com.wasteland.heart                                 installs=     1  CPI=$0.02  CTR=55.56%

  [ANDROID:SAU] Top publishers (L7D):

,campaign_id,os_country,date_utc,publisher_bundle,installs,installs_rejected,spend_usd,cpi,impressions,clicks,retention_d1_pct,retention_d3_pct,ctr_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:IDN,2026-03-04,com.traverse.zhfx.en.gp,4,0,12.55,3.14,284,149,0.0,0.0,52.46
1,jVkXbQ2LIdIKoaQg,ANDROID:IDN,2026-03-04,com.worldance.drama,2,0,0.96,0.48,89,26,0.0,0.0,29.21
2,naoP7qVSZwYbv4GY,ANDROID:BEL,2026-03-04,com.ttee.leeplayer,1,0,0.00,0.00,0,0,0.0,0.0,NaN
3,unbUzFob1WCmTrVD,ANDROID:FRA,2026-03-04,com.bag.fight.backpack.critter.battle.rumble.paws,1,0,0.00,0.00,0,0,0.0,0.0,NaN
4,jVkXbQ2LIdIKoaQg,ANDROID:IDN,2026-03-04,com.livescore,1,0,0.00,0.00,7,0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1059,naoP7qVSZwYbv4GY,ANDROID:SWE,2026-03-03,defense.roguelike.cell.shoot.survivor,1,0,1.15,1.15,72,24,0.0,0.0,33.33
1060,naoP7qVSZwYbv4GY,ANDROID:FRA,2026-03-03,org.smapps.digger,1,0,0.88,0.88,106,28,0.0,0.0,26.42
1061,naoP7qVSZwYbv4GY,ANDROID:SAU,2026-03-03,com.king.knightsrage,1,0,0.08,0.08,6,2,0.0,0.0,33.33
1062,unbUzFob1WCmTrVD,ANDROID:DEU,2026-03-03,wool.match.color.sort.jam.puzzle,1,0,0.77,0.77,37,4,0.0,0.0,10.81
1063,naoP7qVSZwYbv4GY,ANDROID:POL,2026-03-03,com.IdleMagicSchool.jlyt,1,0,0.18,0.18,11,5,0.0,0.0,45.45

## 2. Hourly Install Patterns by Publisher

In [76]:
#2. Hourly Install Trend by Publisher (last 24h, from cv postback)

q_hourly = f"""
SELECT
  {_extra_select_cv}
  DATETIME_TRUNC(DATETIME(timestamp, '{_TZ}'), HOUR) AS hour_kst,
  req.app.bundle AS publisher_bundle,
  COUNT(*) AS installs
FROM `focal-elf-631.prod_stream_view.cv`
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
  AND UPPER(cv.event) = 'INSTALL'
  {_where_filter_cv}
GROUP BY {_extra_group_cv} hour_kst, publisher_bundle
ORDER BY hour_kst ASC, installs DESC
"""

df_hourly = run_query(q_hourly, '2. Hourly Install Trend (24h)')

TOP_N_COUNTRIES = 5

if not df_hourly.empty:
    df_hourly = enrich_publisher_names(df_hourly)
    df_hourly['pub_label'] = df_hourly.apply(
        lambda r: f'{r["publisher_name"][:25]} ({r["publisher_bundle"][:25]})' if r['publisher_name'] else r['publisher_bundle'], axis=1)
    df_hourly['installs'] = pd.to_numeric(df_hourly['installs'], errors='coerce')
    df_hourly['hour_kst'] = pd.to_datetime(df_hourly['hour_kst'])

    import math
    HOUR_MS = 3_600_000 * 0.8

    top_oc = (df_hourly.groupby('os_country')['installs'].sum()
              .sort_values(ascending=False).head(TOP_N_COUNTRIES).index.tolist())
    all_oc = sorted(df_hourly['os_country'].unique())
    if len(all_oc) > TOP_N_COUNTRIES:
        print(f'  {len(all_oc)} OS:Country segments found — showing top {TOP_N_COUNTRIES} by install volume: {top_oc}')
        print(f'  (skipped: {[c for c in all_oc if c not in top_oc]})')

    for oc in top_oc:
        oc_df = df_hourly[df_hourly['os_country'] == oc]
        top_pubs = oc_df.groupby('publisher_bundle')['installs'].sum().sort_values(ascending=False).head(10).index.tolist()
        chart_df = oc_df[oc_df['publisher_bundle'].isin(top_pubs)].copy()
        chart_df['hour_kst'] = chart_df['hour_kst'].astype(str)

        fig = px.bar(chart_df, x='hour_kst', y='installs', color='pub_label',
                     title=f'[{oc}] Hourly Install Trend (Top 10, last 24h, KST)',
                     labels={'hour_kst': 'Time (KST)', 'installs': 'Installs', 'pub_label': 'Publisher'})
        fig.update_traces(width=HOUR_MS)
        fig.update_layout(barmode='stack', height=500, xaxis=dict(tickformat='%b %d %H:%M', dtick=3_600_000))
        fig.show()

        hourly_total = chart_df.groupby('hour_kst')['installs'].transform('sum')
        chart_df['pct'] = (chart_df['installs'] / hourly_total * 100).round(1)
        fig_pct = px.bar(chart_df, x='hour_kst', y='pct', color='pub_label',
                         title=f'[{oc}] Hourly Install Share (Top 10, last 24h, KST)',
                         labels={'hour_kst': 'Time (KST)', 'pct': '% of Installs', 'pub_label': 'Publisher'})
        fig_pct.update_traces(width=HOUR_MS)
        fig_pct.update_layout(barmode='stack', height=500,
                              xaxis=dict(tickformat='%b %d %H:%M', dtick=3_600_000),
                              yaxis=dict(range=[0, 100], dtick=20, ticksuffix='%'))
        fig_pct.show()

        for pub in top_pubs[:3]:
            pub_df = chart_df[chart_df['publisher_bundle'] == pub]
            if pub_df.empty:
                continue
            pub_label = pub_df['pub_label'].iloc[0]
            fig2 = px.bar(pub_df, x='hour_kst', y='installs',
                          title=f'[{oc}] {pub_label[:60]}',
                          labels={'hour_kst': 'Time (KST)', 'installs': 'Installs'})
            fig2.update_traces(width=HOUR_MS)
            max_val = pub_df['installs'].max()
            y_dtick = max(1, math.ceil(max_val / 6)) if max_val > 0 else 1
            fig2.update_layout(height=300, xaxis=dict(tickformat='%b %d %H:%M', dtick=3_600_000),
                               yaxis=dict(dtick=y_dtick, tick0=0))
            fig2.show()
df_hourly

✅ 2. Hourly Install Trend (24h): 1210 rows
  26 OS:Country segments found — showing top 5 by install volume: ['ANDROID:FRA', 'ANDROID:DEU', 'ANDROID:IDN', 'ANDROID:POL', 'ANDROID:GBR']
  (skipped: ['ANDROID:ARE', 'ANDROID:AUS', 'ANDROID:AUT', 'ANDROID:BEL', 'ANDROID:CAN', 'ANDROID:CHE', 'ANDROID:CYP', 'ANDROID:ESP', 'ANDROID:HKG', 'ANDROID:HUN', 'ANDROID:IRL', 'ANDROID:ITA', 'ANDROID:KWT', 'ANDROID:MYS', 'ANDROID:NLD', 'ANDROID:NOR', 'ANDROID:NZL', 'ANDROID:QAT', 'ANDROID:SAU', 'ANDROID:SGP', 'ANDROID:SWE'])

,campaign_id,os_country,hour_kst,publisher_bundle,installs
0,naoP7qVSZwYbv4GY,ANDROID:CAN,2026-03-03 14:00:00,com.pc.sand.loop,1
1,naoP7qVSZwYbv4GY,ANDROID:SGP,2026-03-03 14:00:00,com.and.imi.hcw,1
2,naoP7qVSZwYbv4GY,ANDROID:DEU,2026-03-03 14:00:00,com.wasteland.heart,1
3,naoP7qVSZwYbv4GY,ANDROID:FRA,2026-03-03 14:00:00,com.jedi.renovation,1
4,naoP7qVSZwYbv4GY,ANDROID:FRA,2026-03-03 14:00:00,com.xq.archeroii,1
...,...,...,...,...,...
1205,naoP7qVSZwYbv4GY,ANDROID:POL,2026-03-04 13:00:00,com.innplaylabs.animalkingdomraid,1
1206,naoP7qVSZwYbv4GY,ANDROID:DEU,2026-03-04 13:00:00,com.TreetopCrew.EarthInc,1
1207,unbUzFob1WCmTrVD,ANDROID:DEU,2026-03-04 13:00:00,com.onicore.backpack.rush,1
1208,naoP7qVSZwYbv4GY,ANDROID:DEU,2026-03-04 13:00:00,com.weaver.app.prod,1
1209,unbUzFob1WCmTrVD,ANDROID:GBR,2026-03-04 13:00:00,ai.character.app,1

## 3. D1 / D3 Retention by Publisher

In [77]:
# 3a. OS:Country-level Retention Summary (no publisher breakdown)

q_ret_summary = f"""
SELECT
  {_extra_select}
  SUM(installs) AS installs,
  ROUND(SUM(gross_spend_usd), 2) AS spend_usd,
  ROUND(SAFE_DIVIDE(SUM(gross_spend_usd), NULLIF(SUM(installs), 0)), 2) AS cpi,
  ROUND(SUM(retained_users_d1), 1) AS retained_d1,
  ROUND(SUM(retained_users_d3), 1) AS retained_d3,
  ROUND(SAFE_DIVIDE(SUM(retained_users_d1), NULLIF(SUM(installs), 0)) * 100, 1) AS retention_d1_pct,
  ROUND(SAFE_DIVIDE(SUM(retained_users_d3), NULLIF(SUM(installs), 0)) * 100, 1) AS retention_d3_pct
FROM `moloco-ae-view.athena.fact_dsp_publisher`
WHERE date_utc BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL {LOOKBACK_DAYS} DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
  {_where_filter}
GROUP BY {_extra_group[:-1]}
HAVING installs > 0
ORDER BY installs DESC
"""

df_ret_summary = run_query(q_ret_summary, '3a. Retention by OS:Country')
if not df_ret_summary.empty:
    for col in df_ret_summary.columns:
        if col not in _dim_cols:
            df_ret_summary[col] = pd.to_numeric(df_ret_summary[col], errors='coerce')
    print(f'\n  Retention summary by OS:Country (L{LOOKBACK_DAYS}D, excl. today):')
    display(df_ret_summary)

# 3b. D1/D3 Retention by Publisher (per OS:Country)

q_ret = f"""
SELECT
  {_extra_select}
  publisher.app_market_bundle AS publisher_bundle,
  SUM(installs) AS installs,
  ROUND(SUM(gross_spend_usd), 2) AS spend_usd,
  ROUND(SAFE_DIVIDE(SUM(gross_spend_usd), NULLIF(SUM(installs), 0)), 2) AS cpi,
  ROUND(SUM(retained_users_d1), 1) AS retained_d1,
  ROUND(SUM(retained_users_d3), 1) AS retained_d3,
  ROUND(SAFE_DIVIDE(SUM(retained_users_d1), NULLIF(SUM(installs), 0)) * 100, 1) AS retention_d1_pct,
  ROUND(SAFE_DIVIDE(SUM(retained_users_d3), NULLIF(SUM(installs), 0)) * 100, 1) AS retention_d3_pct
FROM `moloco-ae-view.athena.fact_dsp_publisher`
WHERE date_utc BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL {LOOKBACK_DAYS} DAY) AND DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)
  {_where_filter}
GROUP BY {_extra_group} publisher.app_market_bundle
HAVING installs >= 1
ORDER BY installs DESC
"""

df_ret = run_query(q_ret, '3b. D1/D3 Retention by Publisher')
if not df_ret.empty:
    df_ret = enrich_publisher_names(df_ret)
    str_cols = _dim_cols + ['publisher_bundle', 'publisher_name']
    for col in df_ret.columns:
        if col not in str_cols:
            df_ret[col] = pd.to_numeric(df_ret[col], errors='coerce')

    for oc in sorted(df_ret['os_country'].unique()):
        sub = df_ret[df_ret['os_country'] == oc].sort_values('installs', ascending=False)
        overall_d1 = (sub['retained_d1'].sum() / sub['installs'].sum() * 100) if sub['installs'].sum() > 0 else 0
        overall_d3 = (sub['retained_d3'].sum() / sub['installs'].sum() * 100) if sub['installs'].sum() > 0 else 0
        p10_d1 = sub['retention_d1_pct'].quantile(0.10)
        p10_cpi = sub[sub['cpi'] > 0]['cpi'].quantile(0.10) if (sub['cpi'] > 0).any() else 0
        print(f'\n  [{oc}] {len(sub)} publishers  |  D1={overall_d1:.1f}%  D3={overall_d3:.1f}%  |  P10 D1={p10_d1:.1f}%  P10 CPI=${p10_cpi:.2f}')
        display(sub.head(20).reset_index(drop=True))

    fig = px.scatter(df_ret[df_ret['installs'] >= 3], x='cpi', y='retention_d1_pct', size='installs',
                     hover_name='publisher_bundle', color='os_country',
                     title=f'Publisher CPI vs D1 Retention by OS:Country (L{LOOKBACK_DAYS}D, installs>=3)',
                     labels={'cpi': 'CPI ($)', 'retention_d1_pct': 'D1 Retention %', 'installs': 'Installs'},
                     hover_data={'retention_d3_pct': ':.1f', 'spend_usd': ':,.2f'})
    fig.update_layout(height=500)
    fig.show()

✅ 3a. Retention by OS:Country: 46 rows

  Retention summary by OS:Country (L7D, excl. today):

,campaign_id,os_country,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:FRA,173,241.64,1.40,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:DEU,123,215.52,1.75,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:IDN,123,804.30,6.54,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:POL,109,166.43,1.53,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:GBR,65,82.94,1.28,0.0,0.0,0.0,0.0
5,unbUzFob1WCmTrVD,ANDROID:DEU,49,535.21,10.92,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:HUN,44,51.67,1.17,0.0,0.0,0.0,0.0
7,jVkXbQ2LIdIKoaQg,ANDROID:MYS,34,556.87,16.38,0.0,0.0,0.0,0.0
8,jVkXbQ2LIdIKoaQg,ANDROID:ITA,31,236.31,7.62,0.0,0.0,0.0,0.0
9,unbUzFob1WCmTrVD,ANDROID:FRA,31,283.43,9.14,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:BEL,30,38.62,1.29,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:NLD,25,32.15,1.29,0.0,0.0,0.0,0.0
12,jVkXbQ2LIdIKoaQg,ANDROID:ESP,25,149.57,5.98,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:SAU,25,30.54,1.22,0.0,0.0,0.0,0.0
14,unbUzFob1WCmTrVD,ANDROID:POL,24,230.81,9.62,0.0,0.0,0.0,0.0
15,unbUzFob1WCmTrVD,ANDROID:GBR,23,234.63,10.20,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:SGP,14,13.80,0.99,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:ARE,13,13.50,1.04,0.0,0.0,0.0,0.0
18,naoP7qVSZwYbv4GY,ANDROID:SWE,12,24.57,2.05,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:CHE,10,11.38,1.14,0.0,0.0,0.0,0.0
20,naoP7qVSZwYbv4GY,ANDROID:AUT,10,21.92,2.19,0.0,0.0,0.0,0.0
21,unbUzFob1WCmTrVD,ANDROID:CAN,9,220.11,24.46,0.0,0.0,0.0,0.0
22,unbUzFob1WCmTrVD,ANDROID:HUN,9,45.50,5.06,0.0,0.0,0.0,0.0
23,unbUzFob1WCmTrVD,ANDROID:AUS,8,131.63,16.45,0.0,0.0,0.0,0.0
24,unbUzFob1WCmTrVD,ANDROID:SGP,7,95.45,13.64,0.0,0.0,0.0,0.0
25,jVkXbQ2LIdIKoaQg,ANDROID:HKG,7,538.39,76.91,0.0,0.0,0.0,0.0
26,unbUzFob1WCmTrVD,ANDROID:SWE,6,57.30,9.55,0.0,0.0,0.0,0.0
27,naoP7qVSZwYbv4GY,ANDROID:CAN,5,30.13,6.03,0.0,0.0,0.0,0.0
28,unbUzFob1WCmTrVD,ANDROID:AUT,5,85.19,17.04,0.0,0.0,0.0,0.0
29,naoP7qVSZwYbv4GY,ANDROID:NZL,5,10.08,2.02,0.0,0.0,0.0,0.0
30,naoP7qVSZwYbv4GY,ANDROID:NOR,5,8.20,1.64,0.0,0.0,0.0,0.0
31,jVkXbQ2LIdIKoaQg,ANDROID:CYP,4,16.27,4.07,0.0,0.0,0.0,0.0
32,naoP7qVSZwYbv4GY,ANDROID:IRL,4,6.84,1.71,0.0,0.0,0.0,0.0
33,naoP7qVSZwYbv4GY,ANDROID:KWT,4,4.23,1.06,0.0,0.0,0.0,0.0
34,unbUzFob1WCmTrVD,ANDROID:ARE,4,33.36,8.34,0.0,0.0,0.0,0.0
35,naoP7qVSZwYbv4GY,ANDROID:AUS,4,11.67,2.92,0.0,0.0,0.0,0.0
36,unbUzFob1WCmTrVD,ANDROID:NLD,3,91.43,30.48,0.0,0.0,0.0,0.0
37,unbUzFob1WCmTrVD,ANDROID:SAU,3,65.36,21.79,0.0,0.0,0.0,0.0
38,unbUzFob1WCmTrVD,ANDROID:CHE,3,60.34,20.11,0.0,0.0,0.0,0.0
39,naoP7qVSZwYbv4GY,ANDROID:QAT,3,3.89,1.30,0.0,0.0,0.0,0.0
40,unbUzFob1WCmTrVD,ANDROID:NZL,2,29.39,14.69,0.0,0.0,0.0,0.0
41,unbUzFob1WCmTrVD,ANDROID:BEL,2,60.77,30.39,0.0,0.0,0.0,0.0
42,unbUzFob1WCmTrVD,ANDROID:QAT,1,12.41,12.41,0.0,0.0,0.0,0.0
43,unbUzFob1WCmTrVD,ANDROID:NOR,1,37.67,37.67,0.0,0.0,0.0,0.0
44,unbUzFob1WCmTrVD,ANDROID:IRL,1,20.51,20.51,0.0,0.0,0.0,0.0
45,unbUzFob1WCmTrVD,ANDROID:KWT,1,23.23,23.23,0.0,0.0,0.0,0.0

✅ 3b. D1/D3 Retention by Publisher: 953 rows

  [ANDROID:ARE] 17 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.03

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:ARE,ragdoll.hit.stickman,1,0.04,0.04,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:ARE,me.pokeraid,1,0.00,0.00,0.0,0.0,0.0,0.0
2,unbUzFob1WCmTrVD,ANDROID:ARE,com.multicastgames.butcher,1,2.73,2.73,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:ARE,com.middleeast.huntingsniper,1,0.05,0.05,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:ARE,com.wool.puzzle.game3d,1,0.22,0.22,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:ARE,com.loomgames.pixelflow,1,0.25,0.25,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:ARE,com.battle.worldofartillery,1,0.08,0.08,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:ARE,com.auto.war.crash.arena,1,0.00,0.00,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:ARE,com.hitv.savita,1,0.06,0.06,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:ARE,qiblafinder.prayertimes.qibladirection.hijricalendar,1,0.04,0.04,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:ARE,com.idle.bitcoin.empire,1,0.06,0.06,0.0,0.0,0.0,0.0
11,unbUzFob1WCmTrVD,ANDROID:ARE,com.rheia.patrino,1,0.11,0.11,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:ARE,com.game.space.shooter2,1,0.02,0.02,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:ARE,info.t4w.vp,1,0.21,0.21,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:ARE,com.studion.mergearena,1,0.02,0.02,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:ARE,com.freereels.app,1,0.34,0.34,0.0,0.0,0.0,0.0
16,unbUzFob1WCmTrVD,ANDROID:ARE,com.scores365,1,0.72,0.72,0.0,0.0,0.0,0.0

  [ANDROID:AUS] 12 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.06

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,unbUzFob1WCmTrVD,ANDROID:AUS,com.domobile.applockwatcher,1,0.00,0.00,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:AUS,com.pockethaven.roguelegend,1,4.88,4.88,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:AUS,com.idlesupernaturalschool.jlyt,1,0.04,0.04,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:AUS,com.nebula.mahjongtile,1,0.40,0.40,0.0,0.0,0.0,0.0
4,unbUzFob1WCmTrVD,ANDROID:AUS,com.gramgames.mergedragons,1,0.38,0.38,0.0,0.0,0.0,0.0
5,unbUzFob1WCmTrVD,ANDROID:AUS,com.medieval.punk,1,0.87,0.87,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:AUS,com.Jbm360.ModernTowerDefense,1,0.20,0.20,0.0,0.0,0.0,0.0
7,unbUzFob1WCmTrVD,ANDROID:AUS,com.sportbrain.jewelpuzzle,1,0.86,0.86,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:AUS,com.traverse.zhfx.en.gp,1,0.37,0.37,0.0,0.0,0.0,0.0
9,unbUzFob1WCmTrVD,ANDROID:AUS,com.ftt.msleague_gl,1,1.80,1.80,0.0,0.0,0.0,0.0
10,unbUzFob1WCmTrVD,ANDROID:AUS,com.riftsky.ttl.gb.gp,1,0.06,0.06,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:AUS,com.finetosurvive.master,1,0.28,0.28,0.0,0.0,0.0,0.0

  [ANDROID:AUT] 15 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.04

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:AUT,com.epicoro.castleclashers,1,0.03,0.03,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:AUT,com.snake.slayer,1,0.17,0.17,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:AUT,com.unicostudio.minerfighters,1,0.10,0.10,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:AUT,com.paxiegames.colorflow,1,0.06,0.06,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:AUT,storage.manager.ora,1,0.09,0.09,0.0,0.0,0.0,0.0
5,unbUzFob1WCmTrVD,ANDROID:AUT,com.paxiegames.snakepuzzle,1,1.59,1.59,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:AUT,com.zombie.idleminertycoon,1,0.35,0.35,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:AUT,com.my.hc.rpg.kingdom.simulator,1,0.04,0.04,0.0,0.0,0.0,0.0
8,unbUzFob1WCmTrVD,ANDROID:AUT,com.my.defense,1,1.77,1.77,0.0,0.0,0.0,0.0
9,unbUzFob1WCmTrVD,ANDROID:AUT,autoclicker.clicker.autoclickerapp.autoclickerforgames,1,0.08,0.08,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:AUT,hero.claw.master,1,0.78,0.78,0.0,0.0,0.0,0.0
11,unbUzFob1WCmTrVD,ANDROID:AUT,com.tripledot.woodoku,1,0.09,0.09,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:AUT,train.ride.master,1,0.21,0.21,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:AUT,com.shooterhero,1,0.04,0.04,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:AUT,com.dong.hexwarriors,1,0.42,0.42,0.0,0.0,0.0,0.0

  [ANDROID:BEL] 30 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.04

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:BEL,hero.claw.master,2,0.76,0.38,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:BEL,com.weward,2,0.81,0.41,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:BEL,com.innogames.heroesofhistory,1,0.13,0.13,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:BEL,defense.roguelike.cell.shoot.survivor,1,1.02,1.02,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:BEL,com.pieyel.scrabble,1,0.01,0.01,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:BEL,com.newbeat.gardecor,1,0.29,0.29,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:BEL,com.pocketchamps.game,1,0.91,0.91,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:BEL,com.ImaginativeGames.WealthUpRun,1,0.01,0.01,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:BEL,com.rockbite.zombieoutpost,1,0.27,0.27,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:BEL,com.EvolutionOfGames.EvolutionOfSpecies,1,0.05,0.05,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:BEL,com.block.juggle,1,0.25,0.25,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:BEL,com.ludia.dragons,1,0.13,0.13,0.0,0.0,0.0,0.0
12,unbUzFob1WCmTrVD,ANDROID:BEL,com.naver.linewebtoon,1,1.21,1.21,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:BEL,rail.road.tycoon,1,0.06,0.06,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:BEL,com.wa.cult.empire.tycoon.idle.game,1,0.24,0.24,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:BEL,com.gamebasics.osm,1,0.16,0.16,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:BEL,com.weaver.app.prod,1,0.57,0.57,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:BEL,io.supercent.linkedcubic,1,0.10,0.10,0.0,0.0,0.0,0.0
18,unbUzFob1WCmTrVD,ANDROID:BEL,com.habby.capybara,1,0.14,0.14,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:BEL,com.sadpuppy.lemmings,1,0.05,0.05,0.0,0.0,0.0,0.0

  [ANDROID:CAN] 14 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.08

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,unbUzFob1WCmTrVD,ANDROID:CAN,com.fumbgames.bitcoinempire,1,0.24,0.24,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:CAN,com.loomgames.pixelflow,1,0.35,0.35,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:CAN,com.tombminer.idle.merge,1,0.10,0.10,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:CAN,com.defender.dude,1,1.67,1.67,0.0,0.0,0.0,0.0
4,unbUzFob1WCmTrVD,ANDROID:CAN,com.my.defense,1,2.69,2.69,0.0,0.0,0.0,0.0
5,unbUzFob1WCmTrVD,ANDROID:CAN,com.evodefensetd.gp,1,2.02,2.02,0.0,0.0,0.0,0.0
6,unbUzFob1WCmTrVD,ANDROID:CAN,kr.co.vcnc.android.couple,1,0.00,0.00,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:CAN,com.pc.sand.loop,1,0.07,0.07,0.0,0.0,0.0,0.0
8,unbUzFob1WCmTrVD,ANDROID:CAN,merge.armored.robots,1,0.33,0.33,0.0,0.0,0.0,0.0
9,unbUzFob1WCmTrVD,ANDROID:CAN,com.anibox.catpark,1,0.29,0.29,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:CAN,com.itcgamestudio.arcane.hunter.soul.survivor.monster.action.shooter.rpg,1,0.06,0.06,0.0,0.0,0.0,0.0
11,unbUzFob1WCmTrVD,ANDROID:CAN,com.neorigin.apexgirls,1,0.43,0.43,0.0,0.0,0.0,0.0
12,unbUzFob1WCmTrVD,ANDROID:CAN,com.traverse.zhfx.en.gp,1,10.15,10.15,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:CAN,com.bighelmets.destiny,1,0.66,0.66,0.0,0.0,0.0,0.0

  [ANDROID:CHE] 13 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.04

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,unbUzFob1WCmTrVD,ANDROID:CHE,com.bibiboom.settlementheroes,1,0.04,0.04,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:CHE,com.panteon.arcanearena,1,0.18,0.18,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:CHE,com.actfirstgames.seven,1,0.03,0.03,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:CHE,com.gamebasics.afm,1,0.89,0.89,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:CHE,myfiles.filemanager.fileexplorer.cleaner,1,0.13,0.13,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:CHE,com.eastsidegames.doctorwho,1,0.77,0.77,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:CHE,com.circle38.photocircle,1,0.00,0.00,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:CHE,com.hotheadgames.google.beta.idle_golf,1,0.08,0.08,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:CHE,in.playsimple.wordsearch,1,0.08,0.08,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:CHE,com.sugargames.bot,1,0.20,0.20,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:CHE,house.geeky.mergeevolution,1,0.10,0.10,0.0,0.0,0.0,0.0
11,unbUzFob1WCmTrVD,ANDROID:CHE,mech.fortress.tower.defense.hero.war,1,0.58,0.58,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:CHE,mech.fortress.tower.defense.hero.war,1,0.12,0.12,0.0,0.0,0.0,0.0

  [ANDROID:CYP] 4 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.02

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:CYP,com.hwqgrhhjfd.idlefastfood,1,0.07,0.07,0.0,0.0,0.0,0.0
1,jVkXbQ2LIdIKoaQg,ANDROID:CYP,hero.claw.master,1,0.03,0.03,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:CYP,com.callapp.contacts,1,0.01,0.01,0.0,0.0,0.0,0.0
3,jVkXbQ2LIdIKoaQg,ANDROID:CYP,com.DefaultCompany.HoboLife,1,0.40,0.40,0.0,0.0,0.0,0.0

  [ANDROID:DEU] 151 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.06

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:DEU,com.ecffri.arrows,4,3.26,0.81,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:DEU,com.ebay.kleinanzeigen,4,1.51,0.38,0.0,0.0,0.0,0.0
2,unbUzFob1WCmTrVD,ANDROID:DEU,net.lovoo.android,3,1.80,0.60,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:DEU,defense.roguelike.cell.shoot.survivor,3,5.32,1.77,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:DEU,com.kolka.magic,2,0.25,0.12,0.0,0.0,0.0,0.0
5,unbUzFob1WCmTrVD,ANDROID:DEU,com.pockethaven.roguelegend,2,9.78,4.89,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:DEU,com.bag.fight.backpack.critter.battle.rumble.paws,2,1.02,0.51,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:DEU,com.global.sgdbzseaeu,2,0.21,0.11,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:DEU,train.ride.master,2,1.13,0.57,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:DEU,com.loomgames.pixelflow,2,0.88,0.44,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:DEU,com.iogame.gearworld,2,1.19,0.60,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:DEU,io.supercent.weaponrpg,2,4.56,2.28,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:DEU,com.wa.cult.empire.tycoon.idle.game,2,1.36,0.68,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:DEU,com.vitastudio.mahjong,2,3.34,1.67,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:DEU,com.venturesis.trap,2,1.77,0.89,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:DEU,com.dream.fun.journeymatch,1,0.28,0.28,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:DEU,hero.claw.master,1,1.17,1.17,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:DEU,com.pockethaven.roguelegend,1,0.95,0.95,0.0,0.0,0.0,0.0
18,unbUzFob1WCmTrVD,ANDROID:DEU,com.pixel.art.coloring.color.number.paint.princess,1,0.06,0.06,0.0,0.0,0.0,0.0
19,unbUzFob1WCmTrVD,ANDROID:DEU,com.earlymorningstudio.championsofavan,1,0.79,0.79,0.0,0.0,0.0,0.0

  [ANDROID:ESP] 22 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.06

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.sybogames.subway.surfers.game,2,0.67,0.34,0.0,0.0,0.0,0.0
1,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.multicastgames.butcher,2,1.49,0.74,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.pockethaven.roguelegend,2,0.73,0.37,0.0,0.0,0.0,0.0
3,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.block.juggle,1,0.41,0.41,0.0,0.0,0.0,0.0
4,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.traveler.journey,1,0.01,0.01,0.0,0.0,0.0,0.0
5,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.multicastgames.devour,1,2.10,2.10,0.0,0.0,0.0,0.0
6,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.percent.aos.rollinghero,1,0.70,0.70,0.0,0.0,0.0,0.0
7,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.pocketchamps.game,1,1.65,1.65,0.0,0.0,0.0,0.0
8,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.wallapop,1,0.08,0.08,0.0,0.0,0.0,0.0
9,jVkXbQ2LIdIKoaQg,ANDROID:ESP,es.socialpoint.MonsterLegends,1,0.22,0.22,0.0,0.0,0.0,0.0
10,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.playfocus.king,1,0.85,0.85,0.0,0.0,0.0,0.0
11,jVkXbQ2LIdIKoaQg,ANDROID:ESP,my.arena,1,0.81,0.81,0.0,0.0,0.0,0.0
12,jVkXbQ2LIdIKoaQg,ANDROID:ESP,jp.co.goodroid.hyper.hexaaway,1,0.00,0.00,0.0,0.0,0.0,0.0
13,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.actfirstgames.seven,1,0.29,0.29,0.0,0.0,0.0,0.0
14,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.miui.global.packageinstaller,1,0.04,0.04,0.0,0.0,0.0,0.0
15,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.idle.food.venture.fast,1,0.07,0.07,0.0,0.0,0.0,0.0
16,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.iphonedroid.marca,1,4.24,4.24,0.0,0.0,0.0,0.0
17,jVkXbQ2LIdIKoaQg,ANDROID:ESP,space.galaxy.invasion.iron.machines.war,1,0.19,0.19,0.0,0.0,0.0,0.0
18,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.space.breaker.game,1,0.00,0.00,0.0,0.0,0.0,0.0
19,jVkXbQ2LIdIKoaQg,ANDROID:ESP,com.stormx.growknights,1,0.00,0.00,0.0,0.0,0.0,0.0

  [ANDROID:FRA] 166 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.05

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:FRA,com.block.juggle,6,3.94,0.66,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:FRA,com.dong.hexwarriors,4,1.57,0.39,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:FRA,defense.roguelike.cell.shoot.survivor,4,4.93,1.23,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:FRA,com.epicoro.castleclashers,3,1.54,0.51,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:FRA,com.ecffri.arrows,3,4.26,1.42,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:FRA,com.evodefensetd.gp,3,1.15,0.38,0.0,0.0,0.0,0.0
6,unbUzFob1WCmTrVD,ANDROID:FRA,fr.vinted,3,0.37,0.12,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:FRA,es.socialpoint.DragonCity,3,0.65,0.22,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:FRA,com.appideas.minimonsters,2,0.75,0.38,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:FRA,com.alleylabs.battlegrounds,2,0.75,0.37,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:FRA,com.oxvgames.dicelords,2,2.57,1.29,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:FRA,com.percent.aos.rollinghero,2,0.33,0.17,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:FRA,com.EternalStudio.GearFight,2,1.49,0.75,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:FRA,com.futureplay.boots,2,0.59,0.30,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:FRA,ci.atlasearth.client,2,0.17,0.09,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:FRA,com.pocketchamps.game,2,0.83,0.41,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:FRA,com.naver.linewebtoon,2,4.09,2.04,0.0,0.0,0.0,0.0
17,unbUzFob1WCmTrVD,ANDROID:FRA,com.smallgiantgames.empires,2,1.00,0.50,0.0,0.0,0.0,0.0
18,naoP7qVSZwYbv4GY,ANDROID:FRA,com.lobstargames.dungeon.idle.rpg,2,0.54,0.27,0.0,0.0,0.0,0.0
19,unbUzFob1WCmTrVD,ANDROID:FRA,eu.livesport.FlashScore_com,2,0.12,0.06,0.0,0.0,0.0,0.0

  [ANDROID:GBR] 82 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.03

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:GBR,games.resourcer.hex,3,0.54,0.18,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:GBR,com.ecffri.arrows,2,0.82,0.41,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:GBR,com.easybrain.crossword.puzzles,2,0.51,0.25,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:GBR,com.traverse.zhfx.en.gp,2,3.16,1.58,0.0,0.0,0.0,0.0
4,unbUzFob1WCmTrVD,ANDROID:GBR,com.traverse.zhfx.en.gp,2,19.33,9.66,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:GBR,com.polygon.arena,1,0.02,0.02,0.0,0.0,0.0,0.0
6,unbUzFob1WCmTrVD,ANDROID:GBR,com.gdrhrhw.utxdm,1,1.18,1.18,0.0,0.0,0.0,0.0
7,unbUzFob1WCmTrVD,ANDROID:GBR,ci.atlasearth.client,1,0.20,0.20,0.0,0.0,0.0,0.0
8,unbUzFob1WCmTrVD,ANDROID:GBR,de.motain.iliga,1,0.02,0.02,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:GBR,com.stoneage.privatesub,1,0.25,0.25,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:GBR,io.supercent.weaponrpg,1,1.33,1.33,0.0,0.0,0.0,0.0
11,unbUzFob1WCmTrVD,ANDROID:GBR,magic.deck.champions.duel.collect.card,1,0.74,0.74,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:GBR,com.pockethaven.roguelegend,1,0.78,0.78,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:GBR,com.futureplay.boots,1,0.14,0.14,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:GBR,com.multicastgames.butcher,1,0.24,0.24,0.0,0.0,0.0,0.0
15,unbUzFob1WCmTrVD,ANDROID:GBR,com.skybornegames.travellerscafe,1,0.84,0.84,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:GBR,com.vitastudio.mahjong,1,0.45,0.45,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:GBR,com.newbeat.gardecor,1,0.28,0.28,0.0,0.0,0.0,0.0
18,naoP7qVSZwYbv4GY,ANDROID:GBR,com.serbull.epochwars,1,0.08,0.08,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:GBR,com.hitappsgames.picturebuilder,1,0.18,0.18,0.0,0.0,0.0,0.0

  [ANDROID:HKG] 4 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.24

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:HKG,com.lihkg.app,4,1.47,0.37,0.0,0.0,0.0,0.0
1,jVkXbQ2LIdIKoaQg,ANDROID:HKG,com.intsig.camscanner,1,0.19,0.19,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:HKG,com.com2usholdings.starsailors.android.google.global.normal,1,0.41,0.41,0.0,0.0,0.0,0.0
3,jVkXbQ2LIdIKoaQg,ANDROID:HKG,easy.sudoku.puzzle.solver.free,1,1.14,1.14,0.0,0.0,0.0,0.0

  [ANDROID:HUN] 50 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.04

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:HUN,io.supercent.ageofdinosaurs,2,0.22,0.11,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:HUN,com.epicoro.castleclashers,2,0.59,0.30,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:HUN,com.venturesis.trap,2,0.52,0.26,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:HUN,com.multicastgames.venomSurvive,1,0.07,0.07,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:HUN,com.earlymorningstudio.trident,1,0.12,0.12,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:HUN,com.easybrain.crossword.puzzles,1,0.05,0.05,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:HUN,com.wood.block.sudoku.puzzle.bm,1,0.06,0.06,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:HUN,azurgames.idle.war,1,0.13,0.13,0.0,0.0,0.0,0.0
8,unbUzFob1WCmTrVD,ANDROID:HUN,com.street.bunny,1,0.76,0.76,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:HUN,defense.roguelike.cell.shoot.survivor,1,1.31,1.31,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:HUN,com.earlymorningstudio.championsofavan,1,0.07,0.07,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:HUN,com.nebula.mahjongtile,1,1.12,1.12,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:HUN,com.midcore.monsterscrushidler,1,0.21,0.21,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:HUN,com.funcell.trashinc,1,0.05,0.05,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:HUN,com.playakor.clashofcolor,1,0.07,0.07,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:HUN,com.ludia.dragons,1,0.15,0.15,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:HUN,io.whitesharx.moon,1,0.20,0.20,0.0,0.0,0.0,0.0
17,unbUzFob1WCmTrVD,ANDROID:HUN,com.studio501.cuphero,1,1.48,1.48,0.0,0.0,0.0,0.0
18,naoP7qVSZwYbv4GY,ANDROID:HUN,com.gamehivecorp.taptitans2,1,0.03,0.03,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:HUN,com.bighelmets.destiny,1,0.12,0.12,0.0,0.0,0.0,0.0

  [ANDROID:IDN] 78 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.07

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.traverse.zhfx.en.gp,12,90.77,7.56,0.0,0.0,0.0,0.0
1,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.worldance.drama,7,12.36,1.77,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.freereels.app,6,12.28,2.05,0.0,0.0,0.0,0.0
3,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.naver.linewebtoon,4,6.21,1.55,0.0,0.0,0.0,0.0
4,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.nvsgames.pt,4,4.30,1.08,0.0,0.0,0.0,0.0
5,jVkXbQ2LIdIKoaQg,ANDROID:IDN,defense.roguelike.cell.shoot.survivor,4,47.41,11.85,0.0,0.0,0.0,0.0
6,jVkXbQ2LIdIKoaQg,ANDROID:IDN,hero.claw.master,3,10.48,3.49,0.0,0.0,0.0,0.0
7,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.michatapp.im,3,7.04,2.35,0.0,0.0,0.0,0.0
8,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.bstar.intl,2,3.82,1.91,0.0,0.0,0.0,0.0
9,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.block.juggle,2,17.26,8.63,0.0,0.0,0.0,0.0
10,jVkXbQ2LIdIKoaQg,ANDROID:IDN,my.arena,2,17.58,8.79,0.0,0.0,0.0,0.0
11,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.dong.hexwarriors,2,1.73,0.87,0.0,0.0,0.0,0.0
12,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.iogame.gearworld,2,35.91,17.95,0.0,0.0,0.0,0.0
13,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.bag.fight.backpack.critter.battle.rumble.paws,2,2.30,1.15,0.0,0.0,0.0,0.0
14,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.epicoro.castleclashers,2,11.67,5.84,0.0,0.0,0.0,0.0
15,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.sybogames.subway.surfers.game,2,2.84,1.42,0.0,0.0,0.0,0.0
16,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.netshort.abroad,2,7.40,3.70,0.0,0.0,0.0,0.0
17,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.habby.capybara,2,6.65,3.32,0.0,0.0,0.0,0.0
18,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.wonderpeople.megahitpoker.global,1,0.12,0.12,0.0,0.0,0.0,0.0
19,jVkXbQ2LIdIKoaQg,ANDROID:IDN,com.alleylabs.battlegrounds,1,3.74,3.74,0.0,0.0,0.0,0.0

  [ANDROID:IRL] 5 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.12

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:IRL,park.dragon.pocket.match,1,0.17,0.17,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:IRL,com.deadroad.zhighway,1,0.20,0.20,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:IRL,com.jlyt.SurvivorIsland,1,0.08,0.08,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:IRL,com.mobirate.DeadAheadTactics,1,1.16,1.16,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:IRL,spell.word.screw.sort.puzzle,1,0.28,0.28,0.0,0.0,0.0,0.0

  [ANDROID:ITA] 31 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.03

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.EternalStudio.GearFight,1,0.25,0.25,0.0,0.0,0.0,0.0
1,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.kadka.forknsausage,1,0.05,0.05,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.horus.era.evolution.run,1,0.45,0.45,0.0,0.0,0.0,0.0
3,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.moe.tileshow.animegirl.game,1,2.39,2.39,0.0,0.0,0.0,0.0
4,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.playfocus.royal,1,0.81,0.81,0.0,0.0,0.0,0.0
5,jVkXbQ2LIdIKoaQg,ANDROID:ITA,defense.roguelike.cell.shoot.survivor,1,1.52,1.52,0.0,0.0,0.0,0.0
6,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.rockbite.zombieoutpost,1,0.24,0.24,0.0,0.0,0.0,0.0
7,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.wa.cult.empire.tycoon.idle.game,1,1.42,1.42,0.0,0.0,0.0,0.0
8,jVkXbQ2LIdIKoaQg,ANDROID:ITA,io.supercent.linkedcubic,1,0.80,0.80,0.0,0.0,0.0,0.0
9,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.HomecookedGames.LuckyRPG,1,0.01,0.01,0.0,0.0,0.0,0.0
10,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.mi.poketrade,1,0.02,0.02,0.0,0.0,0.0,0.0
11,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.whalergames.pirateraid,1,3.85,3.85,0.0,0.0,0.0,0.0
12,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.touch2goal.soccer,1,0.03,0.03,0.0,0.0,0.0,0.0
13,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.sybogames.subway.surfers.game,1,3.16,3.16,0.0,0.0,0.0,0.0
14,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.smilegate.outerplane.stove.google,1,0.04,0.04,0.0,0.0,0.0,0.0
15,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.cedargames.tileclear,1,0.40,0.40,0.0,0.0,0.0,0.0
16,jVkXbQ2LIdIKoaQg,ANDROID:ITA,net.ajcloud.universal,1,0.00,0.00,0.0,0.0,0.0,0.0
17,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.innogames.heroesofhistory,1,1.45,1.45,0.0,0.0,0.0,0.0
18,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.bling.ethereumblast,1,0.84,0.84,0.0,0.0,0.0,0.0
19,jVkXbQ2LIdIKoaQg,ANDROID:ITA,com.pockethaven.roguelegend,1,1.17,1.17,0.0,0.0,0.0,0.0

  [ANDROID:KWT] 5 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.03

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,unbUzFob1WCmTrVD,ANDROID:KWT,com.rapid.short.tv,1,0.04,0.04,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:KWT,io.voodoo.paper2,1,0.08,0.08,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:KWT,info.t4w.vp,1,0.03,0.03,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:KWT,io.supercent.bigslimemanyslime,1,0.04,0.04,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:KWT,com.gaman.games.leek.factory.tycoon,1,0.04,0.04,0.0,0.0,0.0,0.0

  [ANDROID:MYS] 28 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.11

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.traverse.zhfx.en.gp,3,44.76,14.92,0.0,0.0,0.0,0.0
1,jVkXbQ2LIdIKoaQg,ANDROID:MYS,defense.roguelike.cell.shoot.survivor,2,27.87,13.94,0.0,0.0,0.0,0.0
2,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.grindrapp.android,2,4.22,2.11,0.0,0.0,0.0,0.0
3,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.ecffri.arrows,2,5.72,2.86,0.0,0.0,0.0,0.0
4,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.bag.fight.backpack.critter.battle.rumble.paws,2,6.78,3.39,0.0,0.0,0.0,0.0
5,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.multicastgames.butcher,1,2.24,2.24,0.0,0.0,0.0,0.0
6,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.litatom.app,1,1.63,1.63,0.0,0.0,0.0,0.0
7,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.mi.poketrade,1,0.00,0.00,0.0,0.0,0.0,0.0
8,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.and.imi.hcw,1,0.12,0.12,0.0,0.0,0.0,0.0
9,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.gstarmc.android,1,0.09,0.09,0.0,0.0,0.0,0.0
10,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.trials.eternity.free,1,1.07,1.07,0.0,0.0,0.0,0.0
11,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.ylogame.kghj,1,0.03,0.03,0.0,0.0,0.0,0.0
12,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.block.juggle,1,12.18,12.18,0.0,0.0,0.0,0.0
13,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.hibox.pickmeupidlegame,1,0.86,0.86,0.0,0.0,0.0,0.0
14,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.ultimagames.magic.tower.defence.game,1,0.26,0.26,0.0,0.0,0.0,0.0
15,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.qxgame.gmerge,1,1.61,1.61,0.0,0.0,0.0,0.0
16,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.runawayplay.flutter,1,0.02,0.02,0.0,0.0,0.0,0.0
17,jVkXbQ2LIdIKoaQg,ANDROID:MYS,jp.co.imagineer.medarotsurvivors,1,4.84,4.84,0.0,0.0,0.0,0.0
18,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.xinghanggame.fish,1,0.41,0.41,0.0,0.0,0.0,0.0
19,jVkXbQ2LIdIKoaQg,ANDROID:MYS,com.bibiboom.settlementheroes,1,1.16,1.16,0.0,0.0,0.0,0.0

  [ANDROID:NLD] 27 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.01

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:NLD,com.mathbrain.sudoku,2,0.24,0.12,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:NLD,com.game.goolny.stickers,1,0.00,0.00,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:NLD,com.pc.sand.loop,1,0.13,0.13,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:NLD,com.unimob.idle.army,1,0.01,0.01,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:NLD,com.zeptolab.thieves.google,1,0.02,0.02,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:NLD,com.fugo.wowguru,1,0.03,0.03,0.0,0.0,0.0,0.0
6,unbUzFob1WCmTrVD,ANDROID:NLD,com.studio501.cuphero,1,3.14,3.14,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:NLD,com.computerlunch.evolution,1,0.12,0.12,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:NLD,com.duolingo,1,0.22,0.22,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:NLD,com.sybogames.subway.surfers.game,1,0.13,0.13,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:NLD,com.alegrium.cong2,1,0.01,0.01,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:NLD,spell.word.screw.sort.puzzle,1,0.31,0.31,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:NLD,com.screw3d.match.nuts.bolts.pin.jam.away.puzzle,1,0.11,0.11,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:NLD,com.LDRLY.cheechandchong,1,0.01,0.01,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:NLD,com.onicore.backpack.rush,1,0.02,0.02,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:NLD,rail.road.tycoon,1,0.09,0.09,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:NLD,com.Beauchamp.Messenger.external,1,0.03,0.03,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:NLD,com.block.juggle,1,0.36,0.36,0.0,0.0,0.0,0.0
18,naoP7qVSZwYbv4GY,ANDROID:NLD,com.zykj.princessknight,1,0.31,0.31,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:NLD,com.bag.fight.backpack.critter.battle.rumble.paws,1,0.20,0.20,0.0,0.0,0.0,0.0

  [ANDROID:NOR] 6 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.05

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:NOR,com.brain.crazy.joygame,1,0.01,0.01,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:NOR,com.evolution.merge,1,0.58,0.58,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:NOR,com.oreon.trapall,1,0.11,0.11,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:NOR,com.appideas.minimonsters,1,0.19,0.19,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:NOR,com.hybridparking.game,1,0.20,0.20,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:NOR,com.popve.dicevmonster,1,0.09,0.09,0.0,0.0,0.0,0.0

  [ANDROID:NZL] 7 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.09

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:NZL,com.evodefensetd.gp,1,0.09,0.09,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:NZL,com.tree.godown,1,0.19,0.19,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:NZL,com.rockydessert.travelcenter,1,0.22,0.22,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:NZL,heroes.battle.strategy.card.game,1,1.16,1.16,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:NZL,com.rbx.battle.android,1,0.09,0.09,0.0,0.0,0.0,0.0
5,unbUzFob1WCmTrVD,ANDROID:NZL,com.IdleMagicSchool.jlyt,1,0.23,0.23,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:NZL,com.nebula.mahjongtile,1,0.45,0.45,0.0,0.0,0.0,0.0

  [ANDROID:POL] 117 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.04

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:POL,com.sybogames.subway.surfers.game,3,0.71,0.24,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:POL,com.studio501.cuphero,3,1.47,0.49,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:POL,com.evodefensetd.gp,2,0.69,0.34,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:POL,hero.claw.master,2,2.60,1.30,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:POL,com.block.juggle,2,1.83,0.92,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:POL,com.pabloleban.IdleSlayer,2,1.06,0.53,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:POL,com.futureplay.boots,2,0.28,0.14,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:POL,com.playstrom.hero.tower,2,0.71,0.36,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:POL,azurgames.idle.war,2,1.02,0.51,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:POL,com.newleaf.app.android.victor,2,0.66,0.33,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:POL,com.idle.food.venture.fast,2,0.23,0.12,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:POL,io.supercent.weaponrpg,2,1.61,0.80,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:POL,heroes.battle.strategy.card.game,2,2.96,1.48,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:POL,com.easybrain.crossword.puzzles,2,1.16,0.58,0.0,0.0,0.0,0.0
14,unbUzFob1WCmTrVD,ANDROID:POL,com.mxdzzus.google,1,0.00,0.00,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:POL,com.playsome.friendsanddragons,1,0.01,0.01,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:POL,com.easybrain.number.sums.puzzle,1,0.23,0.23,0.0,0.0,0.0,0.0
17,unbUzFob1WCmTrVD,ANDROID:POL,com.samsung.android.game.gamehome,1,0.46,0.46,0.0,0.0,0.0,0.0
18,naoP7qVSZwYbv4GY,ANDROID:POL,com.casualjoygames.happymergehome,1,0.01,0.01,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:POL,com.zombie.slasher,1,0.03,0.03,0.0,0.0,0.0,0.0

  [ANDROID:QAT] 4 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.02

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:QAT,com.wasteland.heart,1,0.02,0.02,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:QAT,com.ttt.fortressmerge,1,0.12,0.12,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:QAT,com.bstar.intl,1,0.02,0.02,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:QAT,com.cookapps.idlebackpacker,1,0.04,0.04,0.0,0.0,0.0,0.0

  [ANDROID:SAU] 27 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.02

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:SAU,io.supercent.weaponrpg,2,0.94,0.47,0.0,0.0,0.0,0.0
1,naoP7qVSZwYbv4GY,ANDROID:SAU,com.qxgame.ghard,1,0.05,0.05,0.0,0.0,0.0,0.0
2,unbUzFob1WCmTrVD,ANDROID:SAU,com.aidis.lastcloudiaen,1,0.05,0.05,0.0,0.0,0.0,0.0
3,naoP7qVSZwYbv4GY,ANDROID:SAU,com.habby.archero,1,0.05,0.05,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:SAU,shelter.hero.hapyx,1,0.30,0.30,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:SAU,com.aftaa.magicarcher,1,0.33,0.33,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:SAU,com.zzsjus.google,1,0.16,0.16,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:SAU,train.ride.master,1,0.05,0.05,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:SAU,wp.wattpad,1,0.03,0.03,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:SAU,com.LuB.DeliveryConstruct,1,0.04,0.04,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:SAU,gta.merge.game.gangster,1,0.02,0.02,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:SAU,com.idle.food.venture.fast,1,0.18,0.18,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:SAU,com.casualjoygames.screwproject,1,0.19,0.19,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:SAU,com.pixonic.wwr,1,0.16,0.16,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:SAU,adventure.party.real.life,1,0.19,0.19,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:SAU,heroes.magic.strategy.fantasy.card.game,1,0.02,0.02,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:SAU,com.lilaraum.asteronium,1,0.04,0.04,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:SAU,com.red.sortingstore.android,1,0.11,0.11,0.0,0.0,0.0,0.0
18,unbUzFob1WCmTrVD,ANDROID:SAU,com.vitastudio.mahjong,1,1.92,1.92,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:SAU,com.transportinc.lczyzq,1,0.04,0.04,0.0,0.0,0.0,0.0

  [ANDROID:SGP] 20 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.02

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,naoP7qVSZwYbv4GY,ANDROID:SGP,mech.fortress.tower.defense.hero.war,2,0.25,0.12,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:SGP,com.tp.pmu3d,1,0.87,0.87,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:SGP,com.nexon.ma,1,0.14,0.14,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:SGP,tv.twitch.android.app,1,0.01,0.01,0.0,0.0,0.0,0.0
4,naoP7qVSZwYbv4GY,ANDROID:SGP,com.thecarousell.Carousell,1,0.00,0.00,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:SGP,kr.co.vcnc.android.couple,1,0.00,0.00,0.0,0.0,0.0,0.0
6,unbUzFob1WCmTrVD,ANDROID:SGP,com.michatapp.im,1,0.95,0.95,0.0,0.0,0.0,0.0
7,naoP7qVSZwYbv4GY,ANDROID:SGP,com.vitastudio.mahjong,1,0.94,0.94,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:SGP,com.chamelio.alcatmist,1,0.01,0.01,0.0,0.0,0.0,0.0
9,unbUzFob1WCmTrVD,ANDROID:SGP,com.master.runner,1,0.36,0.36,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:SGP,xiongmao.soap.video.drama,1,0.08,0.08,0.0,0.0,0.0,0.0
11,unbUzFob1WCmTrVD,ANDROID:SGP,com.thecarousell.Carousell,1,0.38,0.38,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:SGP,com.matchingham.flashback.tricky.riddles,1,0.22,0.22,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:SGP,com.waterbear.nightmareswithin,1,0.03,0.03,0.0,0.0,0.0,0.0
14,unbUzFob1WCmTrVD,ANDROID:SGP,com.kokoj.pusherpopquest,1,0.27,0.27,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:SGP,com.puzzle.fun.free.matching3d,1,0.00,0.00,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:SGP,com.iogame.gearworld,1,0.19,0.19,0.0,0.0,0.0,0.0
17,naoP7qVSZwYbv4GY,ANDROID:SGP,com.and.imi.hcw,1,0.05,0.05,0.0,0.0,0.0,0.0
18,unbUzFob1WCmTrVD,ANDROID:SGP,mech.fortress.tower.defense.hero.war,1,1.93,1.93,0.0,0.0,0.0,0.0
19,naoP7qVSZwYbv4GY,ANDROID:SGP,com.orcas.panthia.island.fairyscapes,1,0.21,0.21,0.0,0.0,0.0,0.0

  [ANDROID:SWE] 18 publishers  |  D1=0.0%  D3=0.0%  |  P10 D1=0.0%  P10 CPI=$0.02

,campaign_id,os_country,publisher_bundle,installs,spend_usd,cpi,retained_d1,retained_d3,retention_d1_pct,retention_d3_pct
0,unbUzFob1WCmTrVD,ANDROID:SWE,com.pixelfederation.ts3.train.station.evolution.building.manager.tycoon.simu...,1,0.46,0.46,0.0,0.0,0.0,0.0
1,unbUzFob1WCmTrVD,ANDROID:SWE,games.resourcer.hex,1,0.49,0.49,0.0,0.0,0.0,0.0
2,naoP7qVSZwYbv4GY,ANDROID:SWE,defense.roguelike.cell.shoot.survivor,1,1.15,1.15,0.0,0.0,0.0,0.0
3,unbUzFob1WCmTrVD,ANDROID:SWE,com.king.knightsrage,1,2.21,2.21,0.0,0.0,0.0,0.0
4,unbUzFob1WCmTrVD,ANDROID:SWE,com.multicastgames.butcher,1,1.87,1.87,0.0,0.0,0.0,0.0
5,naoP7qVSZwYbv4GY,ANDROID:SWE,com.sled.surfers.game,1,0.21,0.21,0.0,0.0,0.0,0.0
6,naoP7qVSZwYbv4GY,ANDROID:SWE,com.diamondlife.slots.vegas.free,1,0.17,0.17,0.0,0.0,0.0,0.0
7,unbUzFob1WCmTrVD,ANDROID:SWE,com.Overcurve.Corebound,1,0.09,0.09,0.0,0.0,0.0,0.0
8,naoP7qVSZwYbv4GY,ANDROID:SWE,com.Beauchamp.Messenger.external,1,0.09,0.09,0.0,0.0,0.0,0.0
9,naoP7qVSZwYbv4GY,ANDROID:SWE,com.bighelmets.destiny,1,0.06,0.06,0.0,0.0,0.0,0.0
10,naoP7qVSZwYbv4GY,ANDROID:SWE,com.bag.fight.backpack.critter.battle.rumble.paws,1,0.27,0.27,0.0,0.0,0.0,0.0
11,naoP7qVSZwYbv4GY,ANDROID:SWE,com.DefaultCompany.com.unity.template.mobile2D.idlebrewery,1,0.02,0.02,0.0,0.0,0.0,0.0
12,naoP7qVSZwYbv4GY,ANDROID:SWE,pl.idreams.Dino,1,0.02,0.02,0.0,0.0,0.0,0.0
13,naoP7qVSZwYbv4GY,ANDROID:SWE,air.com.pixelfederation.seaport.explore.collect.trade,1,0.04,0.04,0.0,0.0,0.0,0.0
14,naoP7qVSZwYbv4GY,ANDROID:SWE,beetles.puzzle.solitaire,1,0.01,0.01,0.0,0.0,0.0,0.0
15,naoP7qVSZwYbv4GY,ANDROID:SWE,hero.claw.master,1,1.12,1.12,0.0,0.0,0.0,0.0
16,naoP7qVSZwYbv4GY,ANDROID:SWE,com.hungryshark.android,1,0.01,0.01,0.0,0.0,0.0,0.0
17,unbUzFob1WCmTrVD,ANDROID:SWE,io.supercent.weaponrpg,1,6.27,6.27,0.0,0.0,0.0,0.0

---
## 4. Suspicious Publisher Flags

In [78]:
# 4. Suspicious Publisher Flags (per OS:Country, percentile-based)

MIN_INSTALLS = 10
flags = []

if not df_ret.empty:
    for oc in sorted(df_ret['os_country'].unique()):
        sub = df_ret[df_ret['os_country'] == oc]
        p10_d1 = sub['retention_d1_pct'].quantile(0.10)
        p10_cpi = sub['cpi'].quantile(0.10)

        for _, row in sub.iterrows():
            pub = row['publisher_bundle']
            pub_name = row.get('publisher_name', '')
            reasons = []
            if row['installs'] >= MIN_INSTALLS and row['retention_d1_pct'] < p10_d1:
                reasons.append(f'D1 {row["retention_d1_pct"]:.1f}% < P10 threshold {p10_d1:.1f}%')
            if row['retention_d1_pct'] == 0 and row['installs'] >= 20:
                reasons.append(f'Zero D1 retention with {row["installs"]:.0f} installs')
            if row['installs'] >= MIN_INSTALLS and row['cpi'] < p10_cpi:
                reasons.append(f'CPI ${row["cpi"]:.2f} < P10 threshold ${p10_cpi:.2f}')
            if reasons:
                flags.append({'os_country': oc, 'publisher': pub, 'publisher_name': pub_name,
                              'installs': row['installs'], 'cpi': row['cpi'],
                              'd1_ret': row['retention_d1_pct'], 'reasons': reasons})

if not df_hourly.empty:
    pub_hour_agg = df_hourly.groupby(['os_country', 'publisher_bundle']).agg(
        total=('installs', 'sum'), hours_active=('hour_kst', 'nunique')).reset_index()
    for _, row in pub_hour_agg.iterrows():
        if row['total'] >= 20 and row['hours_active'] <= 2:
            existing = next((f for f in flags if f['publisher'] == row['publisher_bundle']
                             and f.get('os_country') == row['os_country']), None)
            reason = f'Installs concentrated in {row["hours_active"]} hour(s) only'
            if existing:
                existing['reasons'].append(reason)
            else:
                flags.append({'os_country': row['os_country'], 'publisher': row['publisher_bundle'],
                              'installs': row['total'], 'cpi': None, 'd1_ret': None, 'reasons': [reason]})

mode_label = f'Campaigns: {CAMPAIGN_IDS}' if _MODE == 'campaign' else f'Bundles: {MMP_BUNDLE_IDS}'
print(f'{"=" * 60}')
print(f'  Fraud Monitoring Summary')
print(f'  {mode_label} / L{LOOKBACK_DAYS}D')
print(f'{"=" * 60}')

print('\n  Flagging Criteria (per OS:Country, P10 percentile):')
print(f'    1. D1 retention below P10 of segment  (min {MIN_INSTALLS} installs)')
print(f'    2. Zero D1 retention                   (min 20 installs)')
print(f'    3. CPI below P10 of segment            (min {MIN_INSTALLS} installs)')
print(f'    4. Installs in <=2 hours over 24h      (min 20 installs)')

if not df_ret.empty:
    print('\n  Percentile thresholds used:')
    for oc in sorted(df_ret['os_country'].unique()):
        sub = df_ret[df_ret['os_country'] == oc]
        print(f'    [{oc}] D1 P10={sub["retention_d1_pct"].quantile(0.10):.1f}%  CPI P10=${sub["cpi"].quantile(0.10):.2f}')

if flags:
    print(f'\n  {len(flags)} publisher(s) flagged:\n')
    for oc in sorted(set(f['os_country'] for f in flags)):
        oc_flags = [f for f in flags if f['os_country'] == oc]
        print(f'  --- [{oc}] ({len(oc_flags)} flagged) ---')
        for f in sorted(oc_flags, key=lambda x: x['installs'], reverse=True):
            cpi_str = f'${f["cpi"]:.2f}' if f['cpi'] is not None else 'N/A'
            d1_str = f'{f["d1_ret"]:.1f}%' if f['d1_ret'] is not None else 'N/A'
            name = f.get('publisher_name', '')
            label = f'{name} ({f["publisher"]})' if name else f['publisher']
            print(f'  {label[:65]}')
            print(f'    Installs={f["installs"]:.0f}  CPI={cpi_str}  D1={d1_str}')
            for r in f['reasons']:
                print(f'    >> {r}')
        print()
else:
    print('\n  No suspicious publishers flagged')

============================================================
  Fraud Monitoring Summary
  Campaigns: ['naoP7qVSZwYbv4GY', 'unbUzFob1WCmTrVD', 'jVkXbQ2LIdIKoaQg'] / L7D
============================================================

  Flagging Criteria (per OS:Country, P10 percentile):
    1. D1 retention below P10 of segment  (min 10 installs)
    2. Zero D1 retention                   (min 20 installs)
    3. CPI below P10 of segment            (min 10 installs)
    4. Installs in <=2 hours over 24h      (min 20 installs)

  Percentile thresholds used:
    [ANDROID:ARE] D1 P10=0.0%  CPI P10=$0.01
    [ANDROID:AUS] D1 P10=0.0%  CPI P10=$0.04
    [ANDROID:AUT] D1 P10=0.0%  CPI P10=$0.04
    [ANDROID:BEL] D1 P10=0.0%  CPI P10=$0.04
    [ANDROID:CAN] D1 P10=0.0%  CPI P10=$0.06
    [ANDROID:CHE] D1 P10=0.0%  CPI P10=$0.03
    [ANDROID:CYP] D1 P10=0.0%  CPI P10=$0.02
    [ANDROID:DEU] D1 P10=0.0%  CPI P10=$0.05
    [ANDROID:ESP] D1 P10=0.0%  CPI P10=$0.00
    [ANDROID:FRA] D1 P10=0.0%  CPI P10=$0.05
    [ANDROID:GBR] D1 P10=0.0%  CPI P10=$0.03
    [ANDROID:HKG] D1 P10=0.0%  CPI P10=$0.24
    [ANDROID:HUN] D1 P10=0.0%  CPI P10=$0.04
    [ANDROID:IDN] D1 P10=0.0%  CPI P10=$0.06
    [ANDROID:IRL] D1 P10=0.0%  CPI P10=$0.12
    [ANDROID:ITA] D1 P10=0.0%  CPI P10=$0.02
    [ANDROID:KWT] D1 P10=0.0%  CPI P10=$0.03
    [ANDROID:MYS] D1 P10=0.0%  CPI P10=$0.07
    [ANDROID:NLD] D1 P10=0.0%  CPI P10=$0.01
    [ANDROID:NOR] D1 P10=0.0%  CPI P10=$0.05
    [ANDROID:NZL] D1 P10=0.0%  CPI P10=$0.09
    [ANDROID:POL] D1 P10=0.0%  CPI P10=$0.03
    [ANDROID:QAT] D1 P10=0.0%  CPI P10=$0.02
    [ANDROID:SAU] D1 P10=0.0%  CPI P10=$0.02
    [ANDROID:SGP] D1 P10=0.0%  CPI P10=$0.00
    [ANDROID:SWE] D1 P10=0.0%  CPI P10=$0.02

  No suspicious publishers flagged